/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pc.glb 
Author: david.campuzano (https://sketchfab.com/david.campuzano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vaporwave-pc-823082acc7714e17b9d9a12da5459c95
Title: Vaporwave - PC
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pc.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.195}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert11SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert15SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert16SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert10SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert17SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert7SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/pc.glb')
